---

- hosts: all
  become: true
  tasks:
          - name: Ping Servers
            ping:

          - name: install packages
            package:
                    name: 
                        - "{{ package1 }}"
                        - "{{ package2 }}"
                    state: latest
                    update_cache: yes
