---

- hosts: all
  become: true
  tasks:
          - name: remove php and httpd keycloak packages
            package:
                    name: 
                        - "{[ package1 }}"
                        - "{[ package2 }}"
                    state: absent
            when: ansible_distribution == "RedHat" and ansible_version == "8.10"
