- name: Insatall Apache2 web server package
  package:
          name:
                  - "{{ apache2_package }}"
                  - "{{ php_package }}"
          state: latest

- name: Start Apache2 web service
  tags: start_service
  service:
          name: "{{ apache2_service }}"
          state: started
          enabled: yes

- name: Copy default html file for site
  copy:
          src: default_site.html
          dest: /var/www/html/index.txt
          owner: root
          group: root
          mode: 0644
  notify: Restart Apache2

- name: Change e-mail address for admin
  lineinfile:
          path: "{{ apache2_config_file }}"
          regexp: "^ServerAdmin"
          line: ServerAdmin sysadmin@axa-algerie.com
  notify: Restart Apache2
