---

- hosts: all 
  become: true
  pre_tasks:
          - name: Update repository index (RedHat)
            dnf:
                    update_cache: yes
            changed_when: false
            when: ansible_distribution == "RedHat"

          - name: Update repository index (Ubuntu)
            apt:
                    update_cache: yes
            changed_when: false
            when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tags: base
  roles:
          - base

- hosts: workstations
  become: true
  tags: workstations
  roles:
          - workstations

- hosts: web_servers
  become: true
  tags: web_servers
  roles:
          - web_servers

- hosts: db_servers
  become: true
  tags: db_servers
  roles:
          - db_servers

- hosts: file_servers
  become: true
  tags: file_servers
  roles:
          - file_servers
