---

- hosts: all
  become: true
  tasks:
          - name: Ping Servers
            ping:

          - name: install packages
            package:
                    name: "{{ package }}"
                    state: latest
                    update_cache: yes
