---

- hosts: all
  become: true
  tasks:
          - name: Create simone user (RedHat)
            user:
                    name: simone
                    groups: root
                    append: true
            when: ansible_distribution == "RedHat"

          - name: Crate simone user (Ubnutu)
            user:
                    name: simone
                    groups: root
                    append: true
            when: ansible_distribution == "Ubuntu"

          - name: Copy SSH keys to simone user
            authorized_key:
                    user: simone
                    key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDTKzu6uauqzagOAREXmG1Egmxjj8AHk0kIea3onM1z8+MnEJ5XMe3vQt6q/D+cnr/vjipw30cKNuBoCvJAWoC3DA3tk39NcQF2gnoYDcaQGVcb/706Vqyj/EMNJMpC50iublEkmHid4+sxUbnB6B6e/SHK3xm7N7wN0O50pN/NRxslOtreOy9GnJhrtYS0q9Qmq4zKqH7eBXiyth9BtAj9EiBneVHcbeEe/QAkRRLuHF9W4uYZkpwpgxqEK4+088w4vpm6wZt1UY2ASUbDtU+rAsENf968poCi6N5qaSaviYGATCSM+co3XS2edOmYJDzeT6HSObnA2x+0vkjK6zeN SSH key for simone user authentication" 

          - name: Enable public key authentication
            lineinfile:
                    path: /etc/ssh/sshd_config
                    regexp: "PubkeyAuthentication*"
                    line: PubkeyAuthentication yes
            notify: restart_sshd

          - name: Add sudoers file for simone
            ansible.builtin.copy:
                    src: ../files/sudoers_simone
                    dest: /etc/sudoers.d/simone
                    owner: root
                    group: root
                    mode: 0440
  handlers:
          - name: restart_sshd
            ansible.builtin.service:
                    name: sshd
                    state: restarted
